# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
