# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('siblings', models.BooleanField()),
                ('environmental_exposures', models.TextField()),
                ('genetic_mutations', models.TextField()),
                ('status', models.CharField(default='new', max_length=200)),
            ],
        ),
    ]
