# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udn2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('new', 'New Entry'), ('not_accepted', 'Reviewed - Not Accepted'), ('accepted', 'Reviewed - Accepted')], default='new', max_length=15),
        ),
    ]
